language: node_js
node_js:
  - "8"

addons:
  chrome: "stable"

before_install:
  - npm install karma-cli -g
  - npm install concurrently -g

before_script:
  - concurrently 'npm run client' 'npm run server'